############################################################
#
# tomcat 配置
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB
############################################################
#
# 配置数据源信息
#
############################################################
spring:
 application:
  name: foodie-search-service
 profiles:
  active: dev
 datasource: # 数据源的相关配置
  type: com.zaxxer.hikari.HikariDataSource # 数据源类型：HikariCP
  driver-class-name: com.mysql.jdbc.Driver # mysql驱动
  url: jdbc:mysql://localhost:3306/foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
  username: root
  password: 
  hikari:
   connection-timeout: 30000 # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQ
   minimum-idle: 5 # 最小连接数
   maximum-pool-size: 20 # 最大连接数
   auto-commit: true # 自动提交
   idle-timeout: 600000 # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
   pool-name: DateSourceHikariCP # 连接池名字
   max-lifetime: 1800000 # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟
   connection-test-query: SELECT 1
 redis:
  host: 120.78.80.109
  database: 1
  password: zhaoyujie
 servlet:
  multipart:
   max-file-size: 512000 # 500kb
   max-request-size: 512000 # 500kb
############################################################
#
# mybatis 配置
#
############################################################
mybatis:
 type-aliases-package: com.pacee1.search.pojo # 所有POJO类所在包路径
 mapper-locations: classpath:mapper/*.xml # mapper映射文件
 configuration:
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 控制台打印sql
############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
 mappers: com.pacee1.my.mapper.MyMapper
 not-empty: false # 当使用动态sql时，如果有name != null，会自动添加name != '' 不需要
 identity: MYSQL
# 分页插件配置
pagehelper:
 helperDialect: mysql
 supportMethodsArguments: true

